name: tf1_13
channels:
  - menpo
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py_0
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2019.5.15=1
  - cairo=1.14.12=h8948797_3
  - certifi=2019.6.16=py37_1
  - cloudpickle=0.8.1=py_0
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1001
  - dask-core=1.2.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.5.0=py36_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.2.2=py_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - google-pasta=0.1.7=py_0
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.16.1=py37hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py37h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h211956c_0
  - imageio=2.5.0=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.4.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=habf39ab_1
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.2.4=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libblas=3.8.0=5_openblas
  - libcblas=3.8.0=5_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libgpuarray=0.7.6=h14c3975_1003
  - liblapack=3.8.0=5_openblas
  - libopenblas=0.3.3=h5a2b251_3
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.7.1=h8b12597_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mako=1.0.7=py_1
  - markdown=2.6.11=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.0.3=py36h5429711_0
  - matplotlib-base=3.1.0rc1=py36h5f35d83_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - mock=2.0.0=py36_1001
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - notebook=5.7.8=py36_0
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - olefile=0.46=py_0
  - openblas=0.3.5=h9ac9557_1001
  - opencv=3.4.2=py37h6fd60c2_1
  - opencv3=3.1.0=py36_0
  - openssl=1.1.1c=h7b6447c_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=h049681c_0
  - parso=0.4.0=py_0
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.2.2=py37_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.7.1=py37he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pydot=1.4.1=py36_0
  - pygments=2.3.1=py36_0
  - pygpu=0.7.6=py36h3010b51_1000
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py36hd352d35_1
  - pyyaml=5.1.2=py37h7b6447c_0
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py36he1b5a44_0
  - scikit-learn=0.21.2=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - theano=1.0.3=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py_1
  - tornado=6.0.2=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.15.2=py_0
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/palteam/anaconda3/envs/tf1_13

